### ISSUE TITLE
Error installing ParaViewWeb with npm install paraviewweb --save

### ISSUE THREAD

**Issue by rpelorosso** [Kitware/paraviewweb#107]
Hi! I'm trying to install paraviewweb in windows, I have the latest version of nodejs and git. When I run npm install paraviewweb --save, the process fails. I'm sorry about the formatting, I didn't find a way to print verbatim. Do you know what might be happening? 

Thanks!

D:\pww>npm install paraviewweb --save
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

> utf-8-validate@1.2.1 install D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

\
D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm th
at the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: \`C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe\` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

> bufferutil@1.2.1 install D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild

D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node "D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\bufferutil\build\bufferutil.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that t
he path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: \`C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe\` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\pww\node_modules\paraviewweb\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.4.4
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1

> paraviewweb@1.5.1 postinstall D:\pww\node_modules\paraviewweb
> fix-kw-web-suite || true

'fix-kw-web-suite' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "paraviewweb" "--save"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! paraviewweb@1.5.1 postinstall: \`fix-kw-web-suite || true\`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the paraviewweb@1.5.1 postinstall script 'fix-kw-web-suite || true'.
npm ERR! This is most likely a problem with the paraviewweb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fix-kw-web-suite || true
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs paraviewweb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls paraviewweb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\pww\npm-debug.log

D:\pww>

**Comment by jourdain** [comment]
Unfortunately yes... ;-(

We haven't tried to build/develop ParaViewWeb on a Windows system hence the unknown behavior you are noticing.

I guess, if we assume node 4+ and npm 3+, I should be able to remove the post install script which obviously fails on Windows.
But on your system, it seems that "ws" also bring its set of issues...

Anyway, thanks for reporting back...

**Comment by rpelorosso** [comment]
I see, thanks for answering! I don't have a Mac, but I guess it should work fine in Linux, right?

**Comment by jourdain** [comment]
Yes it should. Thanks for your patience.

**Comment by rpelorosso** [comment]
Excellent! I'll try it in Linux then :) Thanks YOU for your hard work! :)

**Comment by mathturtle** [comment]
I work mostly on a paraviewweb based application, but my main development platform is Linux.  So it should work fine on Linux.  You'll probably have to install your own node/npm, the one in my package manager (Ubuntu 15.10) was too old.

**Comment by rpelorosso** [comment]
Thanks @mathturtle ! I'm trying to install it using Arch Linux. My nodejs version is 6.1.0 and my npm version is 3.8.9.

When running npm install paraviewweb, the following happens (pasted below).  Looks like fix-kw-web-suite is missing. Do you know why this might be happening? Thanks!

silencer@myhostname ~]$ npm install paraviewweb
npm WARN deprecated wrench@1.5.8: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.

> bufferutil@1.2.1 install /home/silencer/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/home/silencer/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/home/silencer/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /home/silencer/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/home/silencer/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/home/silencer/node_modules/utf-8-validate/build'

> paraviewweb@1.5.3 postinstall /home/silencer/node_modules/paraviewweb
> fix-kw-web-suite || true

sh: fix-kw-web-suite: command not found
/home/silencer
└─┬ paraviewweb@1.5.3 
  ├─┬ autobahn@0.9.6 
  │ └── crypto-js@3.1.6 
  ├─┬ commander@2.9.0 
  │ └── graceful-readlink@1.0.1 
  ├─┬ gh-pages@0.10.0 
  │ ├── async@1.5.2 
  │ ├─┬ glob@7.0.3 
  │ │ ├─┬ inflight@1.0.4 
  │ │ │ └── wrappy@1.0.1 
  │ │ ├── inherits@2.0.1 
  │ │ ├─┬ minimatch@3.0.0 
  │ │ │ └─┬ brace-expansion@1.1.4 
  │ │ │   ├── balanced-match@0.4.1 
  │ │ │   └── concat-map@0.0.1 
  │ │ ├── once@1.3.3 
  │ │ └── path-is-absolute@1.0.0 
  │ ├── graceful-fs@4.1.2 
  │ ├── q@1.4.1 
  │ ├─┬ q-io@1.13.2 
  │ │ ├─┬ collections@0.2.2 
  │ │ │ └── weak-map@1.0.0 
  │ │ ├── mime@1.3.4 
  │ │ ├── mimeparse@0.1.4 
  │ │ ├── qs@1.2.2 
  │ │ └── url2@0.0.0 
  │ └── wrench@1.5.8 
  ├── shelljs@0.5.3 
  ├── when@3.7.7 
  └─┬ ws@0.8.1 
    ├─┬ bufferutil@1.2.1 
    │ ├── bindings@1.2.1 
    │ └── nan@2.3.3 
    ├── options@0.0.6 
    ├── ultron@1.0.2 
    └── utf-8-validate@1.2.1 

npm WARN enoent ENOENT: no such file or directory, open '/home/silencer/package.json'
npm WARN silencer No description
npm WARN silencer No repository field.
npm WARN silencer No README data
npm WARN silencer No license field.
[silencer@myhostname ~]$

**Comment by jourdain** [comment]
That's expected and you don't need to worry about it. That's why the command it run is:

"fix-kw-web-suite || true"

**Comment by rpelorosso** [comment]
Thanks @jourdain ! What about the

npm WARN enoent ENOENT: no such file or directory, open '/home/silencer/package.json'
npm WARN silencer No description
npm WARN silencer No repository field.
npm WARN silencer No README data
npm WARN silencer No license field.

messages, is that normal?

**Comment by jourdain** [comment]
Are you installing it for one of your web project?
ParaViewWeb is just a Web library and does not provide any executable.
So when you ask npm to install it, npm assume it is to add it into you
local web project.
If npm can't find your package.json, then it print that it couldn't find
your web project.

**Comment by rpelorosso** [comment]
Thank you @jourdain, that makes A LOT of sense. I just have one more question, where can I found the code for this http://www.paraview.org/wp-content/uploads/2014/07/Viz-1024x695.png example?. I know that ParaView 4.1.0 comes with \paraview-4.1\site-packages\paraview\web\pv_web_visualizer.py which seems to be an older version of the Visualizer presented in the linked screenshot, but ParaView 5.0 doesn't seem to come with any python server code examples.

**Comment by jourdain** [comment]
ParaView 5.0 should have the exact same JS code as paraview 4.4.

I don't even know why ParaView 5.0 won't have the Web code (unless you are
on windows).

**Comment by rpelorosso** [comment]
Yes, you're right and I feel like a fool :P It is there, thank you very much!
