### ISSUE TITLE
Twisted receiving a SIGTERM signal.

### ISSUE THREAD

**Issue by rpelorosso** [Kitware/paraviewweb#110]
Hi! 

I'm trying to run the example projects that comes with ParaViewWeb 5. I'm running Linux and ParaView (the app) runs flawlessly. I've copied ParaView to `/opt/paraviewweb ` and run the server with:

`/opt/paraviewweb/bin/pvpython /opt/paraviewweb/lib/paraview-5.0/site-packages/vtk/web/launcher.py /opt/paraviewweb/conf/launch.json`

launch.json can be found here: http://pastebin.com/SzjCiYB9

The server starts without any messages (as expected) and I can access http://localhost:8080/apps/FileViewer/ without issues. The problem is when the client tries to connect to the ParaView server. A ParaView window opens with an empty render (just the blue background and the axis) and suddenly closes. Then the client shows an alert box with the message "Session did not start before timeout expired. Check session logs". 

I've reviewed the log and found that twisted is receiving a SIGTERM signal. Here's the log:

```
2016-05-12 19:16:10+0000 [-] Log opened.
2016-05-12 19:16:10+0000 [-] Site starting on 9003
2016-05-12 19:16:10+0000 [-] Starting factory <twisted.web.server.Site instance at 0x7febe9323128>
2016-05-12 19:16:17+0000 [-] Received SIGTERM, shutting down.
2016-05-12 19:16:17+0000 [twisted.web.server.Site] (TCP Port 9003 Closed)
2016-05-12 19:16:17+0000 [twisted.web.server.Site] Stopping factory <twisted.web.server.Site instance at 0x7febe9323128>
2016-05-12 19:16:17+0000 [-] Main loop terminated.

```

Do you have any ideas on what might be happening? I'm stuck at this point and couldn't make it work. 

Thanks!!
Rodrigo

**Comment by rpelorosso** [comment]
Just more info I've been recollecting:

The client is sending

```{"sessionManagerURL":"http://localhost:8080/paraview/","application":"loader","fileToLoad":"disk_out_ref.ex2","":"undefined"}:```

to `http://localhost:8080/paraview/`but the server is responding 

```{"error": "Session did not start before timeout expired. Check session logs."}```

instead of the session information.

**Comment by jourdain** [comment]
You are missing the readyLine section

```js
"loader": {
        "cmd": [
            "${python_exec}", "-dr", "${python_path}/paraview/web/pv_web_file_loader.py",
            "--port", "${port}", "--data-dir", "${dataDir}", "-f", "--authKey", "${secret}"
        ],
        "ready_line" : "Starting factory"
    },
```

**Comment by rpelorosso** [comment]
That did the trick! thank you! I had adapted the launch.json file from the 4.1 examples and missed that line when reading the example depicted in the launcher.py file. Thank you!
