### ISSUE TITLE
WSS is not supported in paraviewweb 4.1

### ISSUE THREAD

**Issue by aabdulwahed** [Kitware/paraviewweb#114]
Dear All,

I have an issue regarding secure web socket or WSS in paraview web 4.1.

I installed paraview web on a windows server. It works when use default web socket or (WS) over Apache proxy on port 80. 

The issue occurs when I tried to use HTTPS instead of HTTP protocol, I changed the configuration in launcher.config file "SessionURL": "wss://localhost:/wss". I got the following error:

WebSocket connection to 'wss://localhost:9005/wss' failed: Error in connection establishment: net::ERR_CONNECTION_RESET
 Msg:Connection could not be established.

could some one help me out to solve this issue!

please let me know if there any further missing information!

thanks
Ahmed!

**Comment by jourdain** [comment]
Hi Ahmed,

Apache should be the one doing the https/wss. Based on your email, I'm not
sure that you have properly configured Apache so all the communication
(http+ws) are going through port 80.

Once step 1 is done, it is just a matter of configuring apache to use port
443 for both https and wss. The only edit on the launcher will be the
switch from ws:// to wss://.

Seb

**Comment by aabdulwahed** [comment]
Hi sebastian,

could you please check out my Apache configuration from this gist link [apache_https_paraviewweb](https://gist.github.com/aabdulwahed/cdc2698d665ae38500d772bd4bfe65b4)  and my launcher.config from [here](https://gist.github.com/aabdulwahed/133688453feea4a79cafafa8bdc3b753) 

Looking forward to hear from you!

**Comment by jourdain** [comment]
On the apache one:

RewriteRule ^/proxy.*$ wss://${session-to-port:%1}/wss [P]

Should be

RewriteRule ^/proxy.*$ ws://${session-to-port:%1}/ws [P]

On the launcher

"proxy_file" : "/../proxy.txt",
"sessionURL" : "wss://${host}:${port}/wss",

should be

"proxy_file" : "Is it the same as: C:\Program Files
(x86)\pythonLauncher\mapping\proxy.txt",
"sessionURL" : "wss://Apache_host:443/proxy?sessionId=${id}",

I may have missed something else too but that was the obvious part.

Seb

**Comment by aabdulwahed** [comment]
First of all, thanks for response .... second I did your modifications but I got this error in browser

WebSocket connection to 'wss://<APACHE-SERVER>/proxy?sessionId=0368891e-1b8d-11e6-a5b3-000d3a10ab7a' failed: Error during WebSocket handshake: Unexpected response code: 500 

Ahmed!

**Comment by jourdain** [comment]
Make sense, this is not a valid URL: wss:///proxy?sessionId=
0368891e-1b8d-11e6-a5b3-000d3a10ab7a

You just missed the part when I was asking you to put your Apache host name
that I don't know about.

Update your launcher config:

"sessionURL" : "wss://THIS_NEED_TO_BE_YOUR_APACHE_HOST_NAME:443/proxy?
sessionId=${id}",

And don't write THIS_NEED_TO_BE_YOUR_APACHE_HOST_NAME otherwise, it will
still not work.
Fill that part, so it make sense to your setting.

**Comment by aabdulwahed** [comment]
sorry I updated the post .... Actually that's what I did, I added my apache server host name.... still getting the same error

**Comment by jourdain** [comment]
does the URL look right?
Which version of Apache are you using?
Did you enabled all the required modules?

**Comment by aabdulwahed** [comment]
I found that wss is not enabled in apache configuration as shown below 

 SSL Proxy requested for MYSERVER:443 but not enabled [Hint: SSLProxyEngine]
[Mon May 16 18:33:57 2016] [error] proxy: HTTPS: failed to enable ssl support for MYSERVER:443 (MYSERVER)

Does it sound tunneling secure websocket with apache issue  ??

**Comment by aabdulwahed** [comment]
Apache version: 2.2 
Operating System : Windows Server 2012

**Comment by jourdain** [comment]
You need 2.4+ to have the ws forwarding working.

**Comment by aabdulwahed** [comment]
I'm upgrading it right now .... I noticed that Apache 2.2 on Windows OS has issues related to secured web sockets ....

I'll try it and keep you informed!

Thanks Seb ... :+1:

**Comment by aabdulwahed** [comment]
Hi Seb

After upgrading my apache server to version 2.4, I am getting this error

WebSocket connection to 'wss://APACHE-SERVER/proxy?sessionId=1378cc8f-1d03-11e6-921d-000d3a10ab7a/' failed: Error during WebSocket handshake: Unexpected response code: 400

Any thoughts how can I troubleshoot this error  ???

thanks 
Ahmed!

**Comment by jourdain** [comment]
Do you see some output from the Python process? (Logs/1378cc8f-1d03-11e6-921d-000d3a10ab7a.log)
Just to make sure the initial forwarding kind of works.

After that, I've seen error similar to that due to firewalls and/or proxy independent of the machines involved.

Other than that, searching for logs may help to narrow down the issue.

**Comment by aabdulwahed** [comment]
The issue solved .... thanks a million
