### ISSUE TITLE
WSS Unexpected response code: 400

### ISSUE THREAD

**Issue by aabdulwahed** [Kitware/paraviewweb#117]
Hi,

I upgraded my apache server to version 2.4 to enable wss tunnel .... knowing that It works with regular web socket or WS but for secure web socket I got the following error:

WebSocket connection to 'wss://APACHE-SERVER/proxy?sessionId=1378cc8f-1d03-11e6-921d-000d3a10ab7a/' failed: Error during WebSocket handshake: Unexpected response code: 400

Any thoughts how can I troubleshoot this error ???

**Log File error:**

[Wed May 18 17:58:42.497949 2016] [proxy_wstunnel:error] [pid 4400:tid 1108] [client 197.36.130.82:59033] AH02439: error parsing URL //: Invalid host/port
[Wed May 18 18:01:15.956061 2016] [proxy_wstunnel:error] [pid 4400:tid 1112] [client 197.36.130.82:59090] AH02439: error parsing URL //: Invalid host/port

thanks 
Ahmed!

**Comment by jourdain** [comment]
What your apache virtual host config looks like?

It should redirect to ws:// not wss://

**Comment by aabdulwahed** [comment]
Yes, I did that
Kindly check out my Apache virtual host [config](https://gist.github.com/aabdulwahed/538d17d723c0df3b736b8d373d517ed2) and [launcher.config](https://gist.github.com/aabdulwahed/903aecd3243464134b91b150e5de8042)

**Comment by aabdulwahed** [comment]
Also this is a sample of python process log 

```
2016-05-26 08:43:23+0000 [-] Log opened.
2016-05-26 08:43:23+0000 [-] ReapingWampServerFactory starting on 9005
2016-05-26 08:43:23+0000 [-] Starting factory <vtk.web.wamp.ReapingWampServerFactory instance at 0x000000000BA25448>
2016-05-26 08:43:23+0000 [-] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2016-05-26 08:43:23+0000 [-] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
```

And what I get now is this error:

`WebSocket connection to 'wss://MY-APACHE-SERVER:9005/proxy?sessionId=e656549e-231d-11e6-af8d-000d3a10ab7a' failed: Error in connection establishment: net::ERR_CONNECTION_RESET`

I'm trying to check out firewall settings and apache proxy configurations.

**Comment by aabdulwahed** [comment]
Also I have a question ....... does self-signed certificate make a connection reset error ??

**Comment by jourdain** [comment]
Try updating your launcher configuration.

"sessionURL" : "wss://portal.tessra.com/proxy?sessionId=${id}",

"resources" : [ { "host" : "localhost", "port_range" : [9001, 9005] } ],

**Comment by aabdulwahed** [comment]
thanks for your help ... but this raise the first error ... 

` failed: Error during WebSocket handshake: Unexpected response code: 400`

**Comment by jourdain** [comment]
Well I missed that other issue:

"proxy_file" : "/../proxy.txt", 

Should match the file path

C:\Program Files (x86)\pythonLauncher\mapping\proxy.txt

Did you read the documentation? 
http://kitware.github.io/paraviewweb/docs/guides/apache_front_end.html
http://kitware.github.io/paraviewweb/docs/guides/python_launcher.html

**Comment by aabdulwahed** [comment]
The issue was the proxy file .... as you mentioned above.. It is working now ... I'm really appreciate your cooperation ...
thanks seb!
:+1:

**Comment by jourdain** [comment]
Glad to hear you got it working.

**Comment by aabdulwahed** [comment]
there is another issue .... when starting new session on incognito tab I get the following error 

`failed: Error during WebSocket handshake: Unexpected response code: 502`

**Comment by jourdain** [comment]
http://www.checkupdown.com/status/E502.html

**Comment by jourdain** [comment]
Did you try from different browser, not browser tab?

**Comment by aabdulwahed** [comment]
Yep, I tried firefox and chrome

**Comment by jourdain** [comment]
So what was working before?

**Comment by aabdulwahed** [comment]
the viewer is working only when starting first session ..not sure if it is due to ${host}:${port} or 443 in session url  .... then If I try to open the same file I get the error as shown above.

**Comment by jourdain** [comment]
What? ${host}:${port} This should be gone based on what I asked you to fix.

**Comment by aabdulwahed** [comment]
Yep, I did you wrote ....

**Comment by jourdain** [comment]
I think you need to take a minute and look at the documentation and try to understand how things work.
Then you might be able to figure out by yourself what is the piece you missed.

**Comment by aabdulwahed** [comment]
Thanks Seb ... actually I read the documentation multiple times .... but I don't find clear documentation for Parview web - HTTPS setup especially the launcher.config .... do you have a link for it "I mean the launcher.config for wss"

**Comment by jourdain** [comment]
Did you make is work before switching to wss?

**Comment by aabdulwahed** [comment]
Yes, it was working before wss

**Comment by jourdain** [comment]
Well not really, you were using direct connection without going through Apache.

**Comment by aabdulwahed** [comment]
I followed the apache configuration in paraview documentation for ws !

**Comment by jourdain** [comment]
Yes but didn't use the proper configuration for the launcher, which was making the client not going through Apache.

**Comment by aabdulwahed** [comment]
Aha, I got you!
