### ISSUE TITLE
fix-kw-websuite command missing?

### ISSUE THREAD

**Issue by fullflavedave** [Kitware/paraviewweb#125]
I get this error when executing `npm install paraviewweb --save`:

```
> paraviewweb@1.5.12 postinstall /Users/dallen/dev/meteor-client-app/app/node_modules/paraviewweb
> fix-kw-web-suite || true

sh: fix-kw-web-suite: command not found
```

Not sure if it's a problem, but I thought I would mention it.

**Comment by jourdain** [comment]
Thanks Dave, but that's expected.

That's why we have the " || true" to prevent the command from failing. As this is only needed when you run "npm install" from the paraviewweb repo on older npm version.

I should probably get rid of the post install rule and force user to have npm 3+.
