### ISSUE TITLE
Add tags for 'last commit that works with ParaView X.Y'

### ISSUE THREAD

**Issue by mathturtle** [Kitware/paraviewweb#128]
@jourdain I thought of this when I had to update light-viz's ParaView version this weekend and build from master to get the new colormap protocols.  We should probably tag paraviewweb versions as the last version that will work with each ParaView release.  It would help people know what to version of ParaView they need for their application.

**Comment by jourdain** [comment]
ParaViewWeb is a library. That would be the role of the application to properly advertise that. (ArcticViewer, LightViz, Visualizer, ...)

**Comment by mathturtle** [comment]
Well then paraviewweb should document the minimum required paraview version **for each feature** that an application might want to use so that the application developer doesn't have to guess.  It would have saved me a lot of time to know that the colormap image fetching routine I was trying to use required paraview master.  Given the current level of documentation in paraviewweb, I thought just tagging versions as 'everything in here works with ParaView X.Y' would be a much more realistic suggestion.

**Comment by jourdain** [comment]
I agree that should be part of the Widget API. 
If you apply it for the whole repo, then you rule out lot of widgets and components that can work with PV4. The LUT widget was just expecting the latest release, not master.
