### ISSUE TITLE
Cannot read property 'style' of null

### ISSUE THREAD

**Issue by jbeezley** [Kitware/paraviewweb#159]
The following html results in the error `Cannot read property 'style' of null` when loading:
```html
<!DOCTYPE html>
<html>

<head>
  <meta http-equiv="Content-Type" content="text/html; charset = UTF-8">
  <script type="text/javascript" src="ParaViewWeb.js"></script>
</head>

<body>
</body>

</html>
```
It seems to be originating from this line: [src/InfoViz/Native/HistogramSelector/index.js#L42](https://github.com/Kitware/paraviewweb/blob/316beba972bbd24e81e698941117e3ba1270b488/src/InfoViz/Native/HistogramSelector/index.js#L42).  It does load successfully if I move the script tag into the body.

**Comment by aronhelser** [comment]
Makes sense that it would cause an error - there's no 'body' yet. I'll see if I can just substitute 'head'...

**Comment by jourdain** [comment]
ParaViewWeb script might need to be inside body. Not sure why though.

**Comment by aronhelser** [comment]
Using document.head.style seems to be working fine. Should go in with next HistogramSelector features.

**Comment by jbeezley** [comment]
This is admittedly pathological, but does it still work if there is no `head`?  Is there any reason executing this function can't be deferred until a HistogramSelector is actually instantiated?

**Comment by aronhelser** [comment]
OK, I can defer it. I also used either head or body, with a fallback.
Thanks for the feedback.
