### ISSUE TITLE
Module not found: Error: Cannot resolve module 'shader'

### ISSUE THREAD

**Issue by pvandriessche** [Kitware/paraviewweb#178]
I'm taking my first steps with VTK-js and I'm trying to do setup as described on the VTK-js website.
After creating all the files I tried to run "npm run build" I get the follwing error message

> ERROR in ./~/babel-loader?presets[]=es2015,presets[]=react!./~/string-replace-loader?{"multiple":[{"search":"v
tkDebugMacro","replace":"console.debug","flags":"g"},{"search":"vtkErrorMacro","replace":"console.error","flag
s":"g"},{"search":"vtkWarningMacro","replace":"console.warn","flags":"g"}]}!./src/index.js
Module not found: Error: Cannot resolve module 'html-loader' in /home/pvandriessche/MyWebProject/src
 @ ./~/babel-loader?presets[]=es2015,presets[]=react!./~/string-replace-loader?{"multiple":[{"search":"vtkDebu
gMacro","replace":"console.debug","flags":"g"},{"search":"vtkErrorMacro","replace":"console.error","flags":"g"
},{"search":"vtkWarningMacro","replace":"console.warn","flags":"g"}]}!./src/index.js 47:18-46
ERROR in ./~/vtk.js/Sources/Rendering/OpenGL/ImageMapper/index.js
Module not found: Error: Cannot resolve module 'shader' in /home/pvandriessche/MyWebProject/node_modules/vtk.j
s/Sources/Rendering/OpenGL/ImageMapper
 @ ./~/vtk.js/Sources/Rendering/OpenGL/ImageMapper/index.js 44:21-58
ERROR in ./~/vtk.js/Sources/Rendering/OpenGL/PolyDataMapper/index.js
Module not found: Error: Cannot resolve module 'shader' in /home/pvandriessche/MyWebProject/node_modules/vtk.j
s/Sources/Rendering/OpenGL/PolyDataMapper
 @ ./~/vtk.js/Sources/Rendering/OpenGL/PolyDataMapper/index.js 36:21-58
ERROR in ./~/vtk.js/Sources/Rendering/OpenGL/ImageMapper/index.js
Module not found: Error: Cannot resolve module 'shader' in /home/pvandriessche/MyWebProject/node_modules/vtk.j
s/Sources/Rendering/OpenGL/ImageMapper
 @ ./~/vtk.js/Sources/Rendering/OpenGL/ImageMapper/index.js 48:21-58
ERROR in ./~/vtk.js/Sources/Rendering/OpenGL/PolyDataMapper/index.js
Module not found: Error: Cannot resolve module 'shader' in /home/pvandriessche/MyWebProject/node_modules/vtk.j
s/Sources/Rendering/OpenGL/PolyDataMapper
 @ ./~/vtk.js/Sources/Rendering/OpenGL/PolyDataMapper/index.js 40:21-58

> 

Anyone who can help me with t his?

Thanks

**Comment by jourdain** [comment]
Next time report your issue directly on the vtk-js project.
In the mean time, I've just tried it out again, and it seems to be working on my end.

Did you run both of those commands before building it?

```
$ npm install kitware/vtk-js --save-dev
$ npm install kw-web-suite --save-dev
```

Did you get any error?

**Comment by jourdain** [comment]
Which version of npm do you have?

If you have less than 3, that's the issue.

**Comment by pvandriessche** [comment]
I using npm version 4 and added both commands.
I get some errors on missing loaders which I added as well.

2016-07-29 22:00 GMT-05:00 Sebastien Jourdain <notifications@github.com>:

**Comment by jourdain** [comment]
Does it work by adding all the loader by hand?

**Comment by jourdain** [comment]
ok, so npm 4 does not exist. 
What you probably have is Node 4.x with npm 2.x. 
Hence the issue you are facing.
You can either upgrade your node in order to get npm 3 or you can try to run the following command.

```
$ ./node_modules/.bin/fix-kw-web-suite 
```

**Comment by jourdain** [comment]
I tried to upgrade my npm to reproduce your issue and I end up with those versions. Before I had node 5 and some other npm 3 version.

```
$ node --version
v6.3.1
$ npm --version
3.10.5
```

**Comment by jourdain** [comment]
As a reminder on the front page of vtk-js, you can read in the ```Requirements``` section:

```
VTK-JS supports the following development environments:
- Node 5+
- NPM 3+
```

**Comment by pvandriessche** [comment]
It worked!
Thanks a lot for the help!

2016-07-30 11:54 GMT-05:00 Sebastien Jourdain <notifications@github.com>:
