### ISSUE TITLE
Engines field

### ISSUE THREAD

**Issue by TristanWright** [Kitware/paraviewweb#2]
**node:**
0.12.x? 
If we're using any un-babel'ed arrow functions or basic es6 features we should require ≥ 4.0

**npm**
uncertain

**Comment by TristanWright** [comment]
e.g. on Simput, I cannot build it because of a dependency issue.
![screen shot 2016-02-18 at 10 25 42](https://cloud.githubusercontent.com/assets/13318121/13151935/adc24220-d629-11e5-8ac1-bdec6088a610.png)

**Comment by jourdain** [comment]
That why I fixed those issue on npm-dep as well, I'm not using it anymore as I will only get 1 or 2 repos.

**Comment by TristanWright** [comment]
irrelevant
