### ISSUE TITLE
Implement video streaming

### ISSUE THREAD

**Issue by qulyf** [Kitware/paraviewweb#279]
Hello guys, I just use paraviewweb recently, and I'm wondering could video streaming instead of image be implemented based on the current protocol. Though I read the document and the code, I still can't come up with a solution, hoping get some hits from here.

Thanks for your time.

**Comment by aronhelser** [comment]
What kind of project or widget would you like to use video streaming with? Do you have your own video streaming source, or are you interested in the connection between the ParaView server and the web clients, like the scatterplot view?

**Comment by jourdain** [comment]
We don't support video per say. It something we would like to tackle but never got funding for it so far. We were thinking h264 using encoding capabilities of some GPU.

**Comment by felixveysseyre** [comment]
@jourdain Any news on this one ?

**Comment by jourdain** [comment]
not really.

**Comment by jourdain** [comment]
We should have something done by the end of summer.
