### ISSUE TITLE
How to run the example of the paraviewweb in the dva-cli?

### ISSUE THREAD

**Issue by oddcross** [Kitware/paraviewweb#378]
I want to run  the every example components of the paraviewweb so that I can decide which component is I need.Therefore, I want to use the dva-cli as the framework.How can i run the paraviewweb in the dva-cli?Waiting for your answer.

**Comment by jourdain** [comment]
I don't know as I'm not familiar with dva-cli. Although, the ParaViewWeb examples code should be somehow self explanatory. You might be encapsulate an example into a dva UI component as some of them are pure React components.
