### ISSUE TITLE
Is it possible to use only client side for file parsing and rendering?

### ISSUE THREAD

**Issue by OlegJakushkin** [Kitware/paraviewweb#385]
Simple use case: [`itk-vtk-image-viewer`](https://github.com/Kitware/itk-vtk-image-viewer) but for pvd files. Is it possible or ParaView app on server side is a must (if possible tell why)?

**Comment by jourdain** [comment]
The closer thing to itk-vtk-image-viewer is the example [here](https://kitware.github.io/vtk-js/examples/StandaloneSceneLoader.html) which also provide a macro to export a scene from ParaView. That example just highlight the capabilities, but can be extended to let the user choose which array to color by and with which Lookup table.

Currently we haven't done any work on compiling some VTK pieces into WebAssembly like ITK is doing. 

Regarding the question for the server side requirement, I would say if you want complex processing/filtering, the server side approach remain a viable one. While if your data is small enough and you are just interested to look at it, vtk-js can have you cover.

**Comment by OlegJakushkin** [comment]
Thank you, this is extreamly helpfull!=)))
