### ISSUE TITLE
Vagrant up fails when only 1 CPU

### ISSUE THREAD

**Issue by Trophime** [Kitware/paraviewweb#404]
When trying to create a VM using vagrant, there is a problem on machines with only 1 cpu.
Indeed in VagranFile `cpus = cpus / 2` will return `0` which seems to be problematic for `vagrant`

**Comment by jourdain** [comment]
Thanks for your feedback. I guess the goal was to prevent using too much resources from the host system. Maybe we should just set it to 1.

**Comment by Trophime** [comment]
`cpus = [cpus /2, 1].min` would do the trick?

**Comment by Trophime** [comment]
I meant `max` not `min`

**Comment by jourdain** [comment]
do you meam [].max ? Since it can be between 0 and 1.

**Comment by Trophime** [comment]
it should return either cpus/2 or 1...

**Comment by Trophime** [comment]
it seems to work for me ` cpus = [cpus /2, 1].max`

**Comment by jourdain** [comment]
Great just push some changes to fix it...

**Comment by jourdain** [comment]
Thanks for your feedback...
