### ISSUE TITLE
vagrant complains about missing ansible/site.yml

### ISSUE THREAD

**Issue by Trophime** [Kitware/paraviewweb#405]
Next there is no longer any ansible/site.yml when building with vagrant:
```
==> pvw: Running provisioner: ansible...
`playbook` does not exist on the host: /home/LNCMI-G/trophime/paraviewweb/tools/ansible/site.yml
```

**Comment by jourdain** [comment]
The vagrant and ansible playbook have been deprecated so the `ansible` directory that vagrant is trying to use has been renamed `ansible-deprecated`. 

We are working on updating the instruction to use EGL as a rendering backend for ParaView to build ParaViewWeb servers.

But if the machine you want to deploy ParaViewWeb on has a GPU and is a desktop, you should be able to use our ParaView binaries directly.
