### ISSUE TITLE
QueryDataManager + MouseHandler: need to disable default drag behavior on chrome

### ISSUE THREAD

**Issue by zachmullen** [Kitware/paraviewweb#416]
When dragging the mouse on the `img` tag of a QueryDataManager view, on chrome it occasionally uses the default browser behavior of attempting to drag the image and make it follow the cursor. The fix I had to apply was to actually put the `-webkit-user-select: none` style property on the `img` tag itself, rather than just the parent element. It would be great if the image element generated by the QueryDataModel already had this style property set on it so downstreams don't have to set it themselves.

**Comment by jourdain** [comment]
The deal is that `QueryDataManager` is just focusing on fetching the data and providing it to the user. Our usage, in that specific case, is to use the fetched data `as-is`.

But I'll try something and ask you for review...

**Comment by zachmullen** [comment]
That makes sense from an architecture standpoint. If we don't want QueryDataModel to do this, we could always just change the docs for the example `onDataChange` function to also set this style property. Or if there's a way to do it via the MouseHandler, that would be ideal.

**Comment by jourdain** [comment]
The advantage of having it in the queryDataModel is that we can set it only once when the data get fetched.

**Comment by jourdain** [comment]
can you give it a try?

https://github.com/Kitware/paraviewweb/pull/417

**Comment by finetjul** [comment]
Should be closed, right ?
