### ISSUE TITLE
React Widgets static without interaction

### ISSUE THREAD

**Issue by marvinrea** [Kitware/paraviewweb#448]
Hi,
I launched a React project with create-react-app then I ejected webpack config and I installed paraviewweb as this doc : [https://kitware.github.io/paraviewweb/docs/setup.html](url)

but .mcss files seems to not work when I add a React Widget like LookupTableWidget :

![capture d ecran de 2018-04-04 16-54-59](https://user-images.githubusercontent.com/24373811/38316195-711065d6-382a-11e8-93c6-2e487cb43c0b.png)

Is this a common issue ? I did not find anything

**Comment by jourdain** [comment]
How do you build your app? mcss is just a modular css where class composition can be achieved as well as name mangling. A rule should be defined to load them. Otherwise you should get an error message when building.
Based on the information you are provided, it is hard to pin-point the missing part.

**Comment by marvinrea** [comment]
Thank you,
RemoteRenderer works fine in my app but not widgets

I have no error message when building
This is my webpack config to build the app:
I import the rules :
![capture d ecran de 2018-04-05 09-06-02](https://user-images.githubusercontent.com/24373811/38352036-328631c8-38b2-11e8-8619-59a54ea1b501.png)

and I include paraviewweb and wslink paths in loaders:
![capture d ecran de 2018-04-05 09-08-50](https://user-images.githubusercontent.com/24373811/38352010-255db32c-38b2-11e8-9641-a8d8862ca16b.png)

Here is the file (converted in txt for git): 
[webpack.config.prod.txt](https://github.com/Kitware/paraviewweb/files/1878882/webpack.config.prod.txt)

**Comment by jourdain** [comment]
So the part you commented was indeed wrong

```
/*
      {
        test: /\.(sass|scss|mcss)$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader', 'mcss-loader',
          {
            loader: 'postcss-loader',
            options: {
              plugins: () => [autoprefixer('last 2 version', 'ie >= 10')],
            },
          }],
      },
*/
```

Here is the rule that we use to load mcss in ParaViewWeb
https://github.com/Kitware/paraviewweb/blob/master/config/rules-pvw.js#L21-L39

**Comment by marvinrea** [comment]
Ok now I have these errors:
![capture d ecran de 2018-04-05 16-51-57](https://user-images.githubusercontent.com/24373811/38373648-03e744de-38f2-11e8-91b5-adcd92273923.png)

[webpack.config.dev.txt](https://github.com/Kitware/paraviewweb/files/1880532/webpack.config.dev.txt)

**Comment by jourdain** [comment]
It seems you are using Webpack 1? Why is your configuration file so complex?
Can you use a more recent version? What about using this as a starting point?
http://kitware.github.io/paraviewweb/docs/setup.html#Creating-your-own-project

**Comment by marvinrea** [comment]
I started with create-react-app which creates its own configuration, if you want to customize it you have to run the eject script that give you a lot of complex files.

**Comment by jourdain** [comment]
You can see here how the loaders are defined for webpack@1.

https://github.com/Kitware/paraviewweb/blob/v2.5.4/config/webpack.loaders.js#L19-L22

**Comment by jourdain** [comment]
as well as the config 
https://github.com/Kitware/paraviewweb/blob/v2.5.4/documentation/content/docs/setup.md

**Comment by jourdain** [comment]
By using such an old version of webpack you will be missing a lot of optimization... You should really try to setup your project by yourself.

**Comment by marvinrea** [comment]
Ok I tried this, it seems to work
> {
    test: /\.mcss$/,
    loader: 'style!css?modules&importLoaders=1&localIdentName=[name]_[local]_[hash:base64:5]!postcss',
  },

Thank you I will try to setup by myself with webpack 2
