### ISSUE TITLE
How to kill pvpython process after browser closed

### ISSUE THREAD

**Issue by GuDuJian-J-Zhang** [Kitware/paraviewweb#468]
thanks

**Comment by jourdain** [comment]
They are two ways that get handled.

The first one, is automatic. The server process will auto shutdown if no connection are open within a given timeout. (`--timeout 30` argument)

The second approach you can ask the client to stop the server, and you can do that right before the client leave. In Visualizer we do that too which can be seen [here](https://github.com/Kitware/visualizer/blob/master/src/app.js#L53-L59)

**Comment by GuDuJian-J-Zhang** [comment]
@jourdain 
Thanks for your response.
I tried the first solution and set the argument --timeout to 30 in my launcher.json file like this:
![image](https://user-images.githubusercontent.com/21232983/41695059-ebeb99fe-753f-11e8-9245-729790cbca89.png)

But when i close the browser, I run "top" in the terminal, then I got this:
 
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/21232983/41695261-e6cdb474-7540-11e8-9ba3-bd6b6aa95799.png">

It‘s seem that the pvpython process just change to a zombie.

**Comment by jourdain** [comment]
Yes that is expected and as soon as the launcher get another request that process will be fully released. BTW the extra argument is only needed when the default timeout does not match your expectation.
