### ISSUE TITLE
Paraviewweb and JS frameworks

### ISSUE THREAD

**Issue by thompsonx** [Kitware/paraviewweb#470]
Hi,
I would like to ask about using paraviewweb together javascript frameworks. I see that you are developing new components in ReactJS. Our team is planning to develop a web application using paraviewweb and we definitely want to use some JS framework. We are beginners in this area, thus we do not know which one to choose. We are considering Angular and React. I have been testing integration of paraviewweb with both frameworks and both work. On the other hand, I have tried only one basic example with RemoteRenderer, therefore I am not able to say whether I can get into a situation when one of the frameworks would not support a certain feature. Is there any possible issue with the usage of such frameworks together with paraviewweb? Which one would you recommend me to use in order to have some sort of certainty that the most of the paraviewweb features will work? Thank you.

**Comment by jourdain** [comment]
ParaViewWeb is meant to be framework agnostic. So truly it is more a matter of what you prefer to develop with. Lately we've been using vue.js for [ParaView Glance](https://kitware.github.io/paraview-glance/) and it was fine. 
After if you plan to use lots of its React widget, then maybe React would make sense but for remote or local rendering of 3D scene, the core is in plain JavaScript so no framework involved...
