### ISSUE TITLE
ParaViewWeb Multi-user Setup : Apache as a Front-end

### ISSUE THREAD

**Issue by Sagar-Shimpi** [Kitware/paraviewweb#472]
Hi,
I am trying to set up PVW Multi user setup.
As mentioned here (https://kitware.github.io/paraviewweb/docs/multi_user_setup.html), I am working on to set up Apache as User front-end. I am following this tutorial for Apache installation (https://kitware.github.io/paraviewweb/docs/apache_front_end.html).
In the process of Adding a virtual host I am getting error while restarting apache2.
Before that, while executing these commands
$ sudo a2enmod vhost_alias
$ sudo a2enmod proxy
$ sudo a2enmod proxy_http
$ sudo a2enmod proxy_wstunnel
$ sudo a2enmod rewrite

I got this message after every command execution:
"Enabling module proxy.
To activate the new configuration, you need to run: systemctl restart apache2"

At the end while executing  $ sudo service apache2 restart, also I am receiving the same error message. I tried to execute systemctl restart apache2 and I got error "FAILED TO START THE APACHE HTTP SERVER".
Here I have added the snapshot of the same.
![apache_virtualhost_enablingmoduleshttperror2](https://user-images.githubusercontent.com/40625717/43456518-12168aa0-94c4-11e8-8f14-b75d41be347d.PNG)

Also I have added below snippet of my 001-pvw.conf :
![001-pvw conf](https://user-images.githubusercontent.com/40625717/43456553-31efe858-94c4-11e8-8fe4-586a0c3e5650.PNG)

Please help me with this.

Thanks in advance!

**Comment by jourdain** [comment]
The error message says: `ServerName takes one argument` on line 2 you have `ServerName $ ubuntu`.

- arg 1: $
- arg 2: ubuntu

**Comment by jourdain** [comment]
Since I'm at it, the following PATH are not valid ones

- ErrorLog ${APACHE_LOG_DIR}/error.log
- CustomLog ${APACHE_LOG_DIR}/access.log combined

`${APACHE_LOG_DIR}` need to be replaced with a valid path relevant to your setup.

**Comment by Sagar-Shimpi** [comment]
Hi Sebastien,

I appreciate your valuable reply.
It was my mistake in not giving the proper path of THE-DOCUMENT-ROOT and APACHE-LOG-DIR. Thanks for pointing it out.
Now the Apache HTTP Server is started and now I will move on to the multi-user setup of ParaViewWeb.

Regards,
Sagar
