### ISSUE TITLE
paraview web in windows + apache 

### ISSUE THREAD

**Issue by kmilo9999** [Kitware/paraviewweb#477]
Hi.
I followed the instructions described here:
https://kitware.github.io/paraviewweb/docs/windows_10.html

But I cant execute the visualizer on the web browser. When I go to http://paraview/?data=can.ex2
I got this:

[Mon Aug 06 14:41:41.506712 2018] [rewrite:error] [pid 9108:tid 1908] (OS 3)The system cannot find the path specified.  : [client 10.3.131.219:23473] AH00655: mod_rewrite: can't open text RewriteMap file C:/xampp/apache/
[Mon Aug 06 14:41:41.506712 2018] [proxy_wstunnel:error] [pid 9108:tid 1908] [client 10.3.131.219:23473] AH02439: error parsing URL //: Invalid host/port

and on the browser's console:
WebSocket connection to 'ws://paraview/ws' failed: Error during WebSocket handshake: Unexpected response code: 404.

Here are my configuration files:

http://www.wepaste.com/httpd/
http://www.wepaste.com/httpd-vhost/
http://www.wepaste.com/laucher/

and my index.html:
http://www.wepaste.com/myIndex/

I appreciate the help!

Thank you.

**Comment by jourdain** [comment]
When you don't try to load a file, does Visualizer works?

**Comment by jourdain** [comment]
I don't seems to find the content of your files.

Is your host correct? It seems to think that's http://paraview.
Is that expected?

**Comment by kmilo9999** [comment]
Hi,

Wow, I wonder what happened with the content of those files. 
I'm attaching them to this thread.

[paraview_web.zip](https://github.com/Kitware/paraviewweb/files/2263920/paraview_web.zip)

Well, I am following those steps. Basically they added a vhost that responds to the server name paraview. I havent done anything not included in the guide.

Thanks a lot .

**Comment by jourdain** [comment]
I'm not an expert with Windows but looking at the files they mostly seems fine except for the following:
- You do have a duplicate entry in `launcher.config` with the `log_dir` key.
- You are missing the definition of `dataDir`. (You just have __python_exec__ and __visualizer__)

Do you have any files in `D:/ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit/log/` that you could share? (maybe after fixing the above issue)

Also you should try removing that part from the command line (to test out)

```
BEFORE
"${python_exec}", "-dr", "${visualizer}", "--port", "${port}", "--authKey", "${secret}",  "--data", "${dataDir}", "--load-file", "${dataFile}"

AFTER
"${python_exec}", "-dr", "${visualizer}", "--port", "${port}", "--authKey", "${secret}",  "--data", "${dataDir}"
```

**Comment by jourdain** [comment]
`dataDir` is the directory that you want the user to be able to load 3D files from.

**Comment by jourdain** [comment]
Looking at the log, that is indeed the issue the path that get generated for loading the file is invalid so it fails loading it and complains...

```
RuntimeError: File not readable: ${dataDir}\${dataDir}\${dataFile}
```

That doc was contributed by someone in the community that wanted to share how he extended the Visualizer code base to load file at startup.

**Comment by kmilo9999** [comment]
Hi,
I did the suggested changes, and the visualizer is displayed. But the programs hangs and never responds. I checked the browser's console log and I got this:

Visualizer.js:29 WebSocket connection to 'ws://paraview/proxy?sessionId=1eb279e1-99ba-11e8-914a-f4b7e2030bc2&path=ws' failed: Error during WebSocket handshake: Unexpected response code: 400

I check the log and it keeps printing:
[Mon Aug 06 16:48:53.291045 2018] [rewrite:error] [pid 21528:tid 1916] (OS 3)The system cannot find the path specified.  : [client 10.3.131.219:38296] AH00655: mod_rewrite: can't open text RewriteMap file C:/xampp/apache/
[Mon Aug 06 16:48:53.291045 2018] [proxy_wstunnel:error] [pid 21528:tid 1916] [client 10.3.131.219:38296] AH02439: error parsing URL //: Invalid host/port


you think the apache version I am using may be a problem. Should I try with apachehaus?

**Comment by jourdain** [comment]
What is the content of the file `"C://xampp//apache//proxy.txt"` ?

**Comment by kmilo9999** [comment]
Hi,

I changed "//" to "/", and it seems to work at least on the server side. The visualizer starts, but it hangs like if it's waiting for data.
![screenshot_2](https://user-images.githubusercontent.com/16551165/43777827-edd27e8e-9a21-11e8-84f2-c2f3ea80c739.png)

![screenshot_3](https://user-images.githubusercontent.com/16551165/43778124-dc479702-9a22-11e8-9cca-4be6c3087b94.png)

 
Is there any way to debug it ? maybe... wireshark ?

This is my new launcher config:
`{
  "configuration": {
    "host" : "localhost",
    "port" : 9000,
    "endpoint": "paraview",
  "content": "D:/ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit/share/paraview-5.2/web/visualizer/www",
    "proxy_file" : "C:/xampp/apache/proxy.txt",
    "sessionURL" : "ws://paraview:80/proxy?sessionId=${id}&path=ws",
    "timeout" : 30,
    "log_dir" : "D:/ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit/log/",
    "fields" : []
  },
  "resources" : [ {
  "host" : "localhost",
  "port_range" : [9001, 9999]
  } ],
  "properties" : {
    "python_exec" : "D:/ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit/bin/pvpython.exe",
    "visualizer": "D:/ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit/share/paraview-5.2/web/visualizer/server/pvw-visualizer.py",
	"dataDir": "D:/ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit/data/"
  },
  "apps": {
    "visualizer": {
        "cmd": [
            "${python_exec}", "-dr", "${visualizer}", "--port", "${port}", "--authKey", "${secret}",  "--data", "${dataDir}"
        ],
        "ready_line" : "Starting factory"
    }
  }
}`

**Comment by jourdain** [comment]
Looks like everything is fine. You just need to start interacting with the application by clicking on the (+) to add a source or the (File icon) to load a file from your ${dataDir}.

**Comment by jourdain** [comment]
No data is supposed to load at start up since we removed the `"--load-file", "${dataFile}"`.

**Comment by kmilo9999** [comment]
Oh !!!!!!!!!!!!!!!!!!!!!!!!!!
I was expecting to load can.ex2, as it is the value in the get parameter.
Yes, I loaded the sphere and others files, but no can.ex2 :/ . 
You known why?

**Comment by jourdain** [comment]
Did you clicked on the File icon? The (+) will not show you any file, only source object that get created on the fly based on some parameter such as resolution and so on...

Do you see the can.ex2 in your list of files from the Web UI?

**Comment by jourdain** [comment]
Looking at the documentation it seems that `dataDir` needs to be defined with backslash.

```"dataDir": "C:\\SomeFolder\\Data\\Files"```

**Comment by jourdain** [comment]
Meaning for you this should be

```
"dataDir": "D:\\ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit\\data"
```

**Comment by kmilo9999** [comment]
It works !!  I changed it in the index.html file.
Sorry to ask again but, what about the get parameter in the url ?

**Comment by jourdain** [comment]
If you want to load file at startup, you need to add the argument we removed in the command line.

**Comment by jourdain** [comment]
(from the launcher config)

**Comment by kmilo9999** [comment]
Oh!
I thought using this script in the html would do the trick:
```
 <script>
      function getUrlParameter(name) {
  name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
  var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
  var results = regex.exec(location.search);
  return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
};

Visualizer.connect({
  application: 'visualizer',
  dataFile: getUrlParameter('data'),
  dataDir: 'D:\\ParaView-5.2.0-Qt4-OpenGL2-MPI-Windows-64bit\\data\\'
});
    </script>
```

**Comment by jourdain** [comment]
That script is just giving the launcher the information. But if the launcher don't use or care about that argument, nothing is going to happen...

**Comment by kmilo9999** [comment]
Cool!! Thanks a lot for your help.

**Comment by rjsgml5698** [comment]
Hello!!

I have a similar issue. Refer to the above comment and set it as follows.

[work.zip](https://github.com/Kitware/paraviewweb/files/3333596/work.zip)

![image](https://user-images.githubusercontent.com/40594949/60249247-6e880080-98ff-11e9-9b17-7abc22230739.png)

**console log :**
 `WebSocket connection to 'ws://paraview/proxy?sessionId=eec34a00-98b1-11e9-be59-04d3b0fb81c9&path=ws' failed: Error during WebSocket handshake: Unexpected response code: 404`

`Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=%5Bobject%20Event%5D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at d (http://localhost:9000/Visualizer.js:221:315)
    at Qr (http://localhost:9000/Visualizer.js:221:37780)
    at http://localhost:9000/Visualizer.js:221:43658
    at o (http://localhost:9000/Visualizer.js:221:43878)
    at beginWork (http://localhost:9000/Visualizer.js:221:49069)
    at r (http://localhost:9000/Visualizer.js:221:52441)
    at o (http://localhost:9000/Visualizer.js:221:52762)
    at a (http://localhost:9000/Visualizer.js:221:52998)
    at y (http://localhost:9000/Visualizer.js:221:56521)
    at w (http://localhost:9000/Visualizer.js:221:56258)`

I tried all day today, but I seem to be missing something important.

I would really appreciate it if you could help.

Thank you!

**Comment by aronhelser** [comment]
This: ` ws://paraview/proxy?sessionId=eec34a00-98b1-11e9-be59-04d3b0fb81c9&path=ws`
doesn't look like a valid URL. It should point to localhost or your server.
I would suggest asking on the ParaView web support channel,
https://discourse.paraview.org/c/web-support

**Comment by scottwittenburg** [comment]
@aronhelser What is standing out as wrong to you with that url?  I might be missing something.  To me it looks fine as long as `paraview` is resolved to the machine on their network where the Apache with mod_rewrite is listening.

And based on the `access.log` file in the zip file uploaded, it seems those `/proxy` requests are making it to the apache webserver.  I'm not sure why they're not getting handled properly at that point though.

Couple questions:

1. Why don't we see any `/paraview` requests in the access log?  Otherwise it looks like the launcher is running and returning those session urls.

2. Is it possible the other virtual host listening on port 80 in your vhosts config is matching these requests (maybe if "localhost" and "paraview" end up being the same machine)?  Could you try commenting that first one out?

3. Why is your launcher configured to serve the same static content as the apache webserver?  You shouldn't need that `content` key in the launcher config in your case, and maybe it's causing some issue.

**Comment by rjsgml5698** [comment]
Thank you very much for your reply.

I do not know about the server. So I need to study it.

I'm going to build up more background and ask you again.

Thanks! I'll ask you again soon
