### ISSUE TITLE
vtk file rendering?

### ISSUE THREAD

**Issue by AugmentedFoul** [Kitware/paraviewweb#480]
Is it possible to visualize a vtk file using paraviewweb. Im currently working out of react and I need to use something that can visualize vtk files and this looks like it might be the right tool for the job. If its not possible you should consider this a feature request, because it would be useful in the library 

I combed through the api and docs and I cant find a clear way of using anything. Can I get some help to get pointed in the right direction or get started with this library.

**Comment by jourdain** [comment]
ParaViewWeb is meant to be used with Paraview or VTK on the server side for data processing and rendering. So by using either you will be able to read anything that they can read such as a VTK file. But that setup usually require a server with a GPU for good performance. See [RemoteRenderer example](http://kitware.github.io/paraviewweb/examples/RemoteRenderer.html) for more details.

But if you are looking at a more "full JavaScript" for doing so, you should look for [vtk.js](https://kitware.github.io/vtk-js/) or even [ParaView Glance](https://kitware.github.io/paraview-glance/).

**Comment by AugmentedFoul** [comment]
This is my attempt to use straight vtk.js but it is still not working. Im getting an error saying: 
TypeError: view.setRenderable is not a function
![image](https://user-images.githubusercontent.com/12510871/44115211-21789804-9fc2-11e8-903c-037c6153f890.png)


https://pastebin.com/ZCxjnLrm

**Comment by AugmentedFoul** [comment]
I made the edit but the same problem still persists. That said the vtp file is actually showing up in the network tab so it did probably fix a future problem.

**Comment by jourdain** [comment]
Please be more careful when reading/writing code. They are a lot of examples out there that works on the vtk.js site. I know it is not obvious for beginners, but as much as we love helping the community it is time consuming to figure out the simple typo on random codes. Like the one below `vtkOpenGLRenderWindow != FullScreenRenderWindow`... 

```
import vtkOpenGLRenderWindow from 'vtk.js/Sources/Rendering/Misc/FullScreenRenderWindow';
```

I guess you should look at that specific [example](https://kitware.github.io/vtk-js/examples/SimpleCone.html)

**Comment by AugmentedFoul** [comment]
Oh wow, 

Sorry about that. That seemed to fix it thank you very much.

**Comment by AugmentedFoul** [comment]
Ok I thought it was fixed but not quite, there still seems to be an issue with the reader. I keep getting an error.

I thought it was a sync issue, so I used loadData().then, however it is still not working. 
![image](https://user-images.githubusercontent.com/12510871/44121384-a430002c-9fd4-11e8-95a4-37720932e5b4.png)

**Comment by AugmentedFoul** [comment]
Sorry, 

Thought it wouldnt hurt to ask. Thanks for all the help
