### ISSUE TITLE
Advise on new project: react components or native UI component

### ISSUE THREAD

**Issue by nodeCodeNinja** [Kitware/paraviewweb#484]
Hi,

This library is one of the most mature open source implementation I have found so far. Kudos to you for putting it up!

I was looking at remoterenderer example and it seems to use nativeUi renderer component. I see that visualizer is using react rendering component. Will you be maintaining both with feature parity? What would you advise for an app using paraviewweb in angular 6.

I don't also get from API documents or samples,how I can send a request to server. An example of how to change loaded file from UI, how to apply filters with request from UI would also helpful.

If such a thing already exists, please point me in the right direction. I have spent couple of days to see how I can send custom request via wslink and get UI updated with no success.

**Comment by jourdain** [comment]
Thanks for acknowledging our hard work. 

Regarding the rendering components both would live and are fine to use. For Angular 6, I'm guessing the native one would be nicer/easier to use. If ever we improve one of them, porting the improvement to the other will be trivial so I would not worry to much about it. In fact I may implement one within vtk.js at some point which will rely on local interaction style and just send the camera update to the server side. But in any case, switching from one or the other would be strait forward as very little is needed as long as you wrap the 3D view inside an angular component.

For the RPC side, unfortunately the code in our apps remains the only source of documentation (if we can call that documentation). But you can find some good reference here:

Server side:
- https://github.com/Kitware/light-viz/blob/master/server/pvw-light-viz.py#L186-L196
- https://github.com/Kitware/light-viz/blob/master/server/light_viz_protocols.py#L150-L161

Client side: 
- (not the best practice) https://github.com/Kitware/light-viz/blob/master/lib/client.js#L181-L187
- (better practice)
  - https://github.com/Kitware/light-viz/blob/version-2/src/io/Client.js
  - https://github.com/Kitware/light-viz/blob/version-2/src/io/protocols/ProxyName.js
  - https://github.com/Kitware/light-viz/blob/version-2/src/stores/proxy.js#L111-L115

HTH

**Comment by nodeCodeNinja** [comment]
It was too complex, took some time to understand how it is doing, but in the end I managed to do it.
Thanks for the advice.

I do not understand below line of code.
`interactionProxy.Camera3DManipulators = ['Rotate','Pan','Zoom','Pan','Roll','Pan','Zoom','Rotate','Zoom']`

How to control interactions. How to bind them to mouse events. Any pointers related to that would be helpful.
 
For example, How can I switch between a volume representation with rotation and a Stack representation with scrolling through slices.Any examples that shows this would be helpful.

Also volume center is not center if my image when I do rotation. Image goes out of view when I try to rotate. Is there an example that does this already. If not your guidance please.

Thanks in advance!

**Comment by jourdain** [comment]
The action layout is as follow:
Left button, middle button, right button,
Left button + ctrl, middle button + ctrl, middle button + ctrl,
Left button + shift, ...

For the center of rotation, you need to reset the camera. 

For binding the mouse to slice it would be tricky to explain that on a bug tracker. But you will need a custom interactor style from VTK which you will have to bind using some paraview proxy api. This is not that complex to do but without the proper knowledge it could take a while to figure out. We do offer support services if that can help to speed up pieces of your dev that.

**Comment by nodeCodeNinja** [comment]
Able to add a slider on UI to change slice, below code on backend.
Interaction works. Would try to do with mouse scroll, But I do not see a sample or have a way to do in mind yet.

`@exportRPC("pvprotocol.change.changeslice")
    def changeSides(self, N):

        self.image00Display.Slice = int(N)
        self.renderView1.Update()
        self.getApplication().InvokeEvent('UpdateEvent')`

FYI

**Comment by nodeCodeNinja** [comment]
Looks like what I am asking is too difficult.
Please do your best to point me to code/example of custom interactor.
Or let me know in any case so that I can close this issue.

Thanks in advance!

**Comment by jourdain** [comment]
You can manage it on the client side by handling user interaction and translating them to the same call you are making with your slider.
