### ISSUE TITLE
react VtkRenderer component freezes on resize

### ISSUE THREAD

**Issue by kmilo9999** [Kitware/paraviewweb#485]
Hi,

So, I have a VtKRenderer component inside a div tag:

          <div key={'view'+id} style ={{ position: 'relative', display: 'block',width: this.state.myWidth?'50%':'100%',}} >
                            <VtkRenderer
                             key={id}
                             connection={network.getConnection()}
                             client={network.getClient()}
                             viewId={id}

                             stillQuality={100}
                             interactiveQuality={60}
                             stillRatio={1}
                             interactiveRatio={1}
                         />
                         </div>

css width property is managed by a state varibale .(I got code that controls its value ).
When I resize the div tag, the vtk renderer freezes and stops receiving input events. If the browser is resized then the vtk renderer gets  the given size but still doesnt get any input.

Do you have any thoughts on this?

Thanks a lot.

**Comment by kmilo9999** [comment]
Thanks,
I can share you the code I am using. It's just an over simplified version of the multiview example. (I'm just rendering one vtk viewer).

https://justpaste.it/6p7x6

**Comment by kmilo9999** [comment]
Thanks!
Let me know what you can find.

**Comment by jourdain** [comment]
It might be related to an id issue that we may have fixed lately on PVW. Do you use the latest version?

**Comment by kmilo9999** [comment]
I am using  August 14th master version. Should I get a newest one?

**Comment by jourdain** [comment]
You want https://github.com/Kitware/paraviewweb/releases/tag/v3.2.5

**Comment by kmilo9999** [comment]
yuuusssss. Now It does receive the input events and the screen doesnt freeze, Thanks ( I'm assuming  I can just write "paraviewweb": "3.2.5" in the package.json file, right ?).

Although, the renderer view is not resized, only takes the given size after resizing the browser (max or minimize events). I think is a client side problem thought. But let me know if you have any hint on that.

Thanks

**Comment by jourdain** [comment]
yes you can. For the resize, I don't know.
