### ISSUE TITLE
Remove canvas from npm dependency?

### ISSUE THREAD

**Issue by finetjul** [Kitware/paraviewweb#489]
It seems to be a dev-dependency therefore it should not be mandatory.

There are some build issues when installing the canvas npm package on Windows.
Alternatively, canvas-prebuilt could be used instead.

**Comment by omarzion** [comment]
Canvas 1.6.13 seems to be breaking the install on Mac as well, I am able to install Canvas 2.3.1 fine though.  Could you either update the canvas dependency or change it to a dev-dependency as @finetjul suggested?
