### ISSUE TITLE
download binary files from Girder

### ISSUE THREAD

**Issue by CharlesGueunet** [Kitware/paraviewweb#492]
I am using the [downloadFile](https://github.com/Kitware/paraviewweb/blob/master/src/IO/Girder/CoreEndpoints/api.md) method to retrieve some files from [Girder](https://github.com/girder/girder). and I have some troubles with binary files. This method return a Promise, which contains the content of the file in its “data” field. However for binary files, I don’t have the good value for this filed, it differs from the original file.

Using wireshark, I can say that the information sent by the server is the good one. It seems there is a problem in the way paraviewweb decode it.

**Comment by zachmullen** [comment]
If you're looking for a general purpose javascript module for interacting with a Girder REST API, I'd recommend using the `RestClient` from [girder_web_components](https://github.com/girder/girder_web_components). (You don't need to be developing your app in Vue.js to use this part of that library.)

If you just need to download files, but not authenticate or do any complicated operations, you can just use something like [axios](https://www.npmjs.com/package/axios) or even just the native XHR API.

**Comment by jourdain** [comment]
What contentDisposition did you used?

**Comment by CharlesGueunet** [comment]
Thank you for you help, I have finally switched to the Python [girder-client](https://girder.readthedocs.io/en/stable/python-client.html). This one work as expected.
