### ISSUE TITLE
Display and manipulate medical dicom images

### ISSUE THREAD

**Issue by rushikeshsp25** [Kitware/paraviewweb#504]
I am working on a project in which I need to display and annotate dicom as well as nifti images. I want to build this entire solution on web. I am using react for this. I am able to display normal jpg, png images using [ImageRenderer](https://kitware.github.io/paraviewweb/api/React_Renderers_ImageRenderer.html), but it's not displaying dicom image.

My question is, is it possible to display and annotate dicom images using paraviewweb. If yes, how? If no then are there any other options which I can use.

**Comment by jourdain** [comment]
You may want to look into [vtk.js](https://kitware.github.io/vtk-js/index.html)+[itk.js](https://insightsoftwareconsortium.github.io/itk-js/) or an application like [ParaViewGlance](https://kitware.github.io/paraview-glance/index.html). Unless you are planning to use a server for remote rendering, then a ParaViewWeb/VTKWeb approach would be better.

**Comment by jourdain** [comment]
FYI @floryst

**Comment by rushikeshsp25** [comment]
Thanks, @jourdain for your quick response. 
Actually I am new to this field and I just started exploring this. So can you share some proper resources which I can use to build this medical application in react, using itk.js and vtk.js

**Comment by jourdain** [comment]
@floryst, @agirault and @thewtex will be better to give you pointers on how to do it. Especially since they all created applications doing exactly what you are aiming to do.

**Comment by rushikeshsp25** [comment]
Okay, Thank you!

**Comment by thewtex** [comment]
@rushikeshsp25 to quickly get started, try [create-itk-app](https://www.npmjs.com/package/create-itk-app) -- this is *create-react-app* along with the Webpack configuration to use vtk.js and itk.js with React. Then, take a look at the [vtk.js docs](https://kitware.github.io/vtk-js/index.html), [itk.js docs](https://insightsoftwareconsortium.github.io/itk-js/docs/index.html), [ParaView Glance](https://kitware.github.io/paraview-glance/index.html), and a [few recent tutorials](https://discourse.vtk.org/t/new-free-video-tutorials-vtk-js-and-ohif-web-apps/2164).
