### ISSUE TITLE
Issue with Endpoints.txt?

### ISSUE THREAD

**Issue by skoudoro** [Kitware/paraviewweb#511]
Hello all, 

I am trying to run a custom application with Paraviewweb docker image.

I am running the following command: `docker run --gpus all -p 0.0.0.0:9000:80 -v /data/fury-web/:/pvw -v /data/fury-web-data/:/data -e "SERVER_NAME=fury.grg.sice.indiana.edu" -e "PROTOCOL=ws" --restart unless-stopped -dti kitware/paraviewweb:pvw-v5.6.0-egl`.

with the following `endpoint.txt` files:
```
pvw/glance /opt/paraview/share/paraview-5.7/web/glance/www
pvw/lite /opt/paraview/share/paraview-5.7/web/lite/www
pvw/divvy /opt/paraview/share/paraview-5.7/web/divvy/www
pvw/visualizer /opt/paraview/share/paraview-5.7/web/visualizer/www
pvw/flow /opt/paraview/share/paraview-5.7/web/flow/www
pvw /pvw/apps/pvw/www
horizon /pvw/apps/horizon/www
fury /pvw/apps/fury/www
DOCUMENT-ROOT-DIRECTORY /pvw/www/
```

Unfortunately, when I try to reach any endpoints (e.g http://fury.grg.sice.indiana.edu/horizon), I got this error: `The requested URL /horizon was not found on this server.`.  However, it seems to work with the DOCUMENT-ROOT-DIRECTORY as you can see on http://fury.grg.sice.indiana.edu.

What did I do wrong? Do you have any idea? 

Thank you for your feedback.

ps: the full custom app is at http://github.com/fury-gl/fury-web

**Comment by scottwittenburg** [comment]
Not exactly sure what's going on behind the scenes in your setup, but you
might just double-check that, for example, your host system
"/data/fury-web/apps/horizon/www" contains the static content for that
app.  I also notice that you're running the pvw-v5.6.0 container, but some
of your endpoints include a paraview-5.7.  Is that what you meant?

HTH,
Scott

**Comment by jourdain** [comment]
You need the / at the end

**Comment by jourdain** [comment]
Your docker is running on port 9000. Did you setup a front-end apache to get to the docker?

**Comment by skoudoro** [comment]
> Your docker is running on port 9000. Did you setup a front-end apache to get to the docker?

Yes

> You need the / at the end

oh, good catch!, I will try that now

>  I also notice that you're running the pvw-v5.6.0 container, but some
of your endpoints include a paraview-5.7.  Is that what you meant?

No, but good catch too!

Thank you

**Comment by skoudoro** [comment]
Unfortunately, it does not work

> Not exactly sure what's going on behind the scenes in your setup, but you
might just double-check that, for example, your host system
"/data/fury-web/apps/horizon/www" contains the static content for that
app.

They contain static content to check if everything is working as expected (I planned to add a python server and a complete application after this simple test.

Do you mean, I can not have a static page?

> You need the / at the end

I added them but it does not work (`/` at the end of `www` or I misunderstood?). For creating this app, I followed this template: https://github.com/Kitware/paraviewweb-demo/tree/master/pvw

Concerning the apache setup, I followed your tutorial. This is the setup:
```
<VirtualHost *:80>
    ProxyPreserveHost On
    ServerName fury.grg.sice.indiana.edu

    ErrorLog /var/log/httpd/fury-error.log
    CustomLog /var/log/httpd/fury-access.log combined

    # Handle websocket forwarding
    ProxyPass /proxy ws://localhost:9000/proxy

    # Main server
    ProxyPass / http://localhost:9000/
    ProxyPassReverse / http://localhost:9000/
 <VirtualHost>
```

**Comment by skoudoro** [comment]
Thank you for your guidance @jourdain and @scottwittenburg. I fixed my issue. closing
