### ISSUE TITLE
npm install --save tries to execute bash script using cmd.exe on Windows

### ISSUE THREAD

**Issue by AlbertoPa** [Kitware/paraviewweb#533]
Installing paravieweb on Windows fails when issuing

`npm install paraviewweb --save`

The error message is:

```
npm ERR! code 1
npm ERR! path C:\Users\alber\Desktop\pvw\node_modules\paraviewweb
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ./config/prebuild.sh
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
```

which seems to point to the issue that cmd.exe is being invoked to execute prebuild.sh.

Are there additional settings that need to be taken to install on Windows (it would seem it should work based on https://kitware.github.io/paraviewweb/docs/setup.html#Getting-ParaViewWeb-source-code-for-contributing )

Thank you.

**Comment by jourdain** [comment]
Can I ask why you would like to use the `paraviewweb` js package in your project? For the last 4 years, we've been using `vtk.js` instead for all our VTK and ParaView Web related project rather than `paraviewweb`. vtk.js is the way forward assuming that was your intent.

**Comment by AlbertoPa** [comment]
My goal is to integrate something that can interface to paraview server, so anything that does that works. It wasn't clear to me what is the most up to date and it seemed to me vtk.js was more basic and require more effort to interface to data readers and renderers, but if that's not the case, I'll be happy to reconsider!

Thanks,
Alberto

**Comment by AlbertoPa** [comment]
Thank you @jourdain
