### ISSUE TITLE
An error occurred when npm install was installed。./config/prebuild.sh '.' is not an internal or external command, nor is it a executable program  Or batch file.

### ISSUE THREAD

**Issue by xuwenxiang1030** [Kitware/paraviewweb#542]
An error occurred when npm install was installed。./config/prebuild.sh '.' is not an internal or external command, nor is it a executable program  Or batch file.

**Comment by jourdain** [comment]
That repository is deprecated and, therefore, not maintained. If you aim to use VTK/ParaView Web, please use vtk.js.
